#+SETUPFILE: level-0.org
#+TITLE: Projects

Several open-source projects to which I contribute.
* Simgrid
Website: http://simgrid.gforge.inria.fr

Simgrid is a free software to simulate a wide range of distributed systems: grid, P2P, cloud, MPI applications. It is
a joint effort of CNRS, Inria and various universities. Its simulation models have been theoretically and
experimentally assessed.

I mostly use and contribute to [[http://simgrid.gforge.inria.fr/simgrid/3.18/doc/group__SMPI__API.html][SMPI]], a module of Simgrid which can realisticaly simulate unmodified MPI applications.
* Roaring bitmaps
  Website: http://roaringbitmap.org
** CRoaring
   Github repository: https://github.com/RoaringBitmap/CRoaring
** PyRoaring
   Github repository: https://github.com/Ezibenroc/PyRoaringBitMap
* Platypus
  Website: https://projetpp.github.io

Platypus is a modular and open source question answering framework. Its main purpose is to answer to questions asked in
a natural language (e.g. in English). For instance, it answers correctly to the question:

#+begin_quote
What is the birth date of the president of the United States?
#+end_quote

For more information, read the [[file:doc/platypus_report.pdf][report]] or the [[file:doc/platypus_slides.pdf][slides]]. This work was initially a student project. It was done as part of
the master's first year at the ENS Lyon, in a team of seven. The project has then been sold to [[https://lexistems.com/][Lexistems]] and is no
longer actively maintained by ourselves.
